[BF] # Bloom Filter

    [BF.para] # parameters
    num_bits = 2577607
    num_hash = 5

    [BF.test] # testing metrics
    sample = 0.3             # Sample 30% records as a sample
    insert = ["RATE"]        # Metric for insertion
    lookup = ["RATE", "PRC"] # Metric for looking up

    [BF.data] # testing data
    data = "../data/records.bin"  # Path to data, being either relative or absolute.
                                  # But remember to QUOTE it!
                                  # Relative to `build/`.
    format = [["flowkey", "padding"], [13, 2]]
    # Format of records in data
    # Grammar:
    #   | Field Name | Viable Length | Further Constraints                   |
    #   |:-----------|:--------------|:--------------------------------------|
    #   | flowkey    | 4, 8, 13      | Specify exactly once                  |
    #   | timestamp  | 1, 2, 4, 8    | In microseconds. Specify at most once |
    #   | length     | 1, 2, 4, 8    | Specify at most once                  |
    #   | padding    | > 0           | None                                  |



[CM] # Count Min Sketch

  [CM.para]
  depth = 2
  width = 1000
  #width = 80001

  [CM.data]
  cnt_method = "InPacket"
  data = "../data/t.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [CM.test]
  update = ["RATE"]
  query = ["RATE", "ARE", "AAE"]

  [CM.ch]
  cnt_no_ratio = 0.3
  width_cnt = [10, 7]
  no_hash = [3]

[ACS] # Additive Counter Sharing
  
  [ACS.config]
    sketch = ["CM"]
    data = "../data/data-100K.bin"
    cnt_method = "InPacket"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
    get_method = "THETA_METHOD"
    iternum = 4
    init_val = 0.1
    step_val = 2.0
    clip = 0
    ratio = 4
    K = 4

  [ACS.CM]
    [ACS.CM.para]
      depth = 2
      width = 80001
    [ACS.CM.test]
      update = ["RATE"]
      query = ["RATE", "ARE", "AAE", "RCD"]

  [ACS.FlowRadar]
    [ACS.FlowRadar.para]
      flow_filter_bit = 1000000
      flow_filter_hash = 50
      count_table_num = 500000
      count_table_hash = 5
      #flow_filter_bit = 10000
      #flow_filter_hash = 5
      #count_table_num = 5000
      #count_table_hash = 5
    [ACS.FlowRadar.test]
      update = ["RATE"]
      decode = ["TIME", "ARE", "AAE", "RATIO", "ACC", "PODF"]
      decode_podf = 0.01

  [ACS.HP]
    [ACS.HP.para]
      depth = 15
      width = 8222
    [ACS.HP.data]
      hx_method = "TopK"
      threshold_heavy_hitter = 100
    [ACS.HP.test]
      update = ["RATE"]
      heavyhitter = ["TIME", "ARE", "PRC", "RCL", "RCD"]
  
  [ACS.DT]
    [ACS.DT.para]
      num_hash = 2
      num_group = 2500
    [ACS.DT.data]
      hx_method = "Percentile"
      threshold_heavy_hitter = 0.0009173226287898038
    [ACS.DT.test]
      update = ["RATE"]
      query = ["RATE", "ARE", "AAE"]
      heavyhitter = ["TIME", "ARE", "PRC", "RCL", "RCD"]

[HP] # Hash Pipe

  [HP.para]
  depth = 3
  width = 300

  [HP.data]
  hx_method = "TopK"
  threshold_heavy_hitter = 300
  cnt_method = "InPacket"
  data = "../data/t.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [HP.test]
  update = ["RATE"]
  heavyhitter = ["TIME", "ARE", "PRC", "RCL"]

[FlowRadar] # Flow Radar

  [FlowRadar.para]
    #flow_filter_bit = 1000000
    #flow_filter_hash = 50
    #count_table_num = 500000
    #count_table_hash = 5
    flow_filter_bit = 10000
    flow_filter_hash = 5
    count_table_num = 5000
    count_table_hash = 5
  
  [FlowRadar.data]
    data = "../data/t.bin"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
  
  [FlowRadar.test]
    update = ["RATE"]
    decode = ["TIME", "ARE", "AAE", "RATIO", "ACC", "PODF"]
    decode_podf = 0.01

[DT] # Deltoid

  [DT.para]
  num_hash = 2
  num_group = 2500

  [DT.data]
  hx_method = "Percentile"
  threshold_heavy_hitter = 0.0009173226287898038
  cnt_method = "InPacket"
  data = "../data/data-100K.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [DT.test]
  update = ["RATE"]
  query = ["RATE", "ARE", "AAE"]
  heavyhitter = ["TIME", "ARE", "PRC", "RCL", "RCD"]

  [DT.ch]
  cnt_no_ratio = 0.09
  width_cnt = [9, 10]
  no_hash = [3]

[CBF] # Counting Bloom Filter

  [CBF.para]
    num_cnt = 200000
    num_hash = 3
    cnt_length = 4

  [CBF.data]
    data = "../data/records.bin"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [CBF.test]
    sample = 0.3
    insert = ["RATE"]
    lookup = ["RATE", "PRC"]